[linux]
vm1 ansible_host=linux6909linda1.centralus.cloudapp.azure.com vm_number=1 node_fqdn=linux6909linda1.centralus.cloudapp.azure.com
vm2 ansible_host=linux6909linda2.centralus.cloudapp.azure.com vm_number=2 node_fqdn=linux6909linda2.centralus.cloudapp.azure.com
vm3 ansible_host=linux6909linda3.centralus.cloudapp.azure.com vm_number=3 node_fqdn=linux6909linda3.centralus.cloudapp.azure.com

[linux:vars]
ansible_user=n01276909
ansible_ssh_private_key_file=/Users/lindamol/.ssh/id_rsa
ansible_connection=ssh
